backend:
  name: github
  repo: forumbjbi-org/bjbi.github.io
  branch: main
  client_id: Ov23liexmWimJSk0uipz


media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "artikel"
    label: "Artikel"
    folder: "artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
